services:
  db:
    image: postgres:15
    container_name: finance_db
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: finance_user
      POSTGRES_PASSWORD: finance_pass
      POSTGRES_DB: finance_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U finance_user"]
      interval: 5s
      timeout: 3s
      retries: 5

  web:
    build: .
    container_name: finance_app
    restart: unless-stopped
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    command: flask run --host=0.0.0.0

volumes:
  postgres_data:

