"""Increase password_hash length

Revision ID: 811a4a1adaa3
Revises: b75b6cfa3ff7
Create Date: 2025-06-16 19:59:03.976700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '811a4a1adaa3'
down_revision = 'b75b6cfa3ff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=512),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
